apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redis
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.8.5
    plugin:
      name: helm-valuesfrom
      parameters:
        - name: valuesFrom
          array:
            - '{"kind":"secret","name":"redis-values"}'
            - '{"kind":"configmap","name":"redis-values"}'
    # helm:
      # releaseName: sealed-secrets

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
